/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { Penjualan, Kendaraan, Customer, Barang, AlatBerat } from '../types';
import { AlertCircle, Calculator, Info } from 'lucide-react';

interface PenjualanFormProps {
  initialData: Penjualan | null;
  salesList: Penjualan[];
  kendaraanList: Kendaraan[];
  customerList: Customer[];
  barangList: Barang[];
  alatBeratList: AlatBerat[];
  onSubmit: (data: Penjualan | Omit<Penjualan, 'id'>) => void;
  onCancel: () => void;
}

export default function PenjualanForm({
  initialData,
  salesList,
  kendaraanList,
  customerList,
  barangList,
  alatBeratList,
  onSubmit,
  onCancel,
}: PenjualanFormProps) {
  // 1. Core Fields
  const [tanggal, setTanggal] = useState('');
  const [divisi, setDivisi] = useState<Penjualan['divisi']>('Tambang');
  const [tipePenjualan, setTipePenjualan] = useState<Penjualan['tipePenjualan']>('Tunai');
  const [noInvoice, setNoInvoice] = useState('');
  const [keterangan, setKeterangan] = useState('');
  const [isNoInvoiceManuallyEdited, setIsNoInvoiceManuallyEdited] = useState(false);

  // 2. Integrated Database Fields
  const [selectedNoPolisi, setSelectedNoPolisi] = useState('');
  const [statusKendaraan, setStatusKendaraan] = useState<Kendaraan['statusKendaraan']>('INTERNAL');
  const [sopir, setSopir] = useState('');

  const [selectedCustomerId, setSelectedCustomerId] = useState('');
  const [selectedBarangId, setSelectedBarangId] = useState('');
  const [selectedAlatBeratId, setSelectedAlatBeratId] = useState('');

  const [satuan, setSatuan] = useState<Penjualan['satuan']>('RIT');
  const [kuantiti, setKuantiti] = useState<number>(0);
  const [harga, setHarga] = useState<number>(0);
  const [diskon, setDiskon] = useState<number>(0);

  // Calculated states (for UI preview, though we'll compute them for submit)
  const [mel, setMel] = useState<number>(0);
  const [total, setTotal] = useState<number>(0);

  // Error messages
  const [errorMsg, setErrorMsg] = useState('');

  // Track initialization so form fields are initialized ONLY ONCE per transaction edit/add session,
  // preventing background polling or master list updates from wiping out user inputs.
  const initializedIdRef = React.useRef<string | null>(null);

  // Auto-generate suggested invoice number on mount if creating new
  useEffect(() => {
    const currentId = initialData ? initialData.id : 'NEW_TRANSACTION';
    if (initializedIdRef.current === currentId) {
      return;
    }
    initializedIdRef.current = currentId;

    if (initialData) {
      // Edit mode
      setTanggal(initialData.tanggal);
      setDivisi(initialData.divisi);
      setTipePenjualan(initialData.tipePenjualan);
      setNoInvoice(initialData.noInvoice);
      setKeterangan(initialData.keterangan || '');

      setSelectedNoPolisi(initialData.noPolisi);
      setStatusKendaraan(initialData.statusKendaraan);
      setSopir(initialData.sopir);

      // Find customer ID by code
      const cust = customerList.find((c) => c.kodeCustomer === initialData.kodeCustomer);
      if (cust) setSelectedCustomerId(cust.id);

      // Find barang ID by code
      const item = barangList.find((b) => b.kodeBarang === initialData.kodeBarang);
      if (item) setSelectedBarangId(item.id);

      // Find alat berat ID by code
      const eq = alatBeratList.find((e) => e.kodeAlat === initialData.kodeAlat);
      if (eq) setSelectedAlatBeratId(eq.id);

      setSatuan(initialData.satuan);
      setKuantiti(initialData.kuantiti);
      setHarga(initialData.harga);
      setDiskon(initialData.diskon);
    } else {
      // Add mode
      const today = new Date().toISOString().split('T')[0];
      setTanggal(today);
      setDivisi('Tambang');
      setTipePenjualan('Tunai');
      setNoInvoice(''); // will be auto-generated by the useEffect below
      
      setKeterangan('');
      setSelectedNoPolisi('');
      setSopir('');
      setStatusKendaraan('INTERNAL');
      setSelectedCustomerId('');
      setSelectedBarangId('');
      setSelectedAlatBeratId('');
      setSatuan('RIT');
      setKuantiti(1);
      setHarga(0);
      setDiskon(0);
    }
  }, [initialData, kendaraanList, customerList, barangList, alatBeratList]);

  // Auto-generate suggested invoice number based on selected date (tanggal) and salesList in Add mode (resets each month)
  useEffect(() => {
    if (!initialData && tanggal && !isNoInvoiceManuallyEdited) {
      const dateParts = tanggal.split('-');
      if (dateParts.length >= 2) {
        const year = dateParts[0];
        const month = dateParts[1];
        const currentYM = `${year}-${month}`;

        let maxSeq = 0;
        salesList.forEach((item) => {
          if (item.tanggal && item.tanggal.startsWith(currentYM)) {
            let seq = NaN;
            // Strategy 1: split by slash
            const parts = item.noInvoice.split('/');
            const lastPart = parts[parts.length - 1];
            if (lastPart) {
              seq = parseInt(lastPart, 10);
            }
            // Strategy 2: regex if Strategy 1 fails
            if (isNaN(seq)) {
              const match = item.noInvoice.match(/(\d+)/g);
              if (match && match.length > 0) {
                seq = parseInt(match[match.length - 1], 10);
              }
            }
            if (!isNaN(seq) && seq > maxSeq) {
              maxSeq = seq;
            }
          }
        });

        const nextSeq = maxSeq + 1;
        const paddedSeq = String(nextSeq).padStart(3, '0');
        setNoInvoice(`INV/${year}/${month}/${paddedSeq}`);
      }
    }
  }, [tanggal, salesList, initialData, isNoInvoiceManuallyEdited]);

  // Handle vehicle select change
  const handleVehicleChange = (noPol: string) => {
    setSelectedNoPolisi(noPol);
    const vehicle = kendaraanList.find((k) => k.noPolisi === noPol);
    if (vehicle) {
      setSopir(vehicle.sopir);
      setStatusKendaraan(vehicle.statusKendaraan);
    } else {
      setSopir('');
      setStatusKendaraan('INTERNAL');
    }
  };

  // Live total and MEL calculations
  useEffect(() => {
    // 1. Calculate Total: kuantiti * (harga - diskon)
    const netPrice = Math.max(0, harga - diskon);
    setTotal(kuantiti * netPrice);

    // 2. Calculate MEL
    const customer = customerList.find((c) => c.id === selectedCustomerId);
    const item = barangList.find((b) => b.id === selectedBarangId);

    if (customer && customer.namaCustomer.trim().toLowerCase() === 'manyung') {
      setMel(0); // If customer name is exactly "Manyung" (case-insensitive), MEL is 0
    } else if (item) {
      setMel(item.nilaiMel); // Else, MEL value is loaded from the items database
    } else {
      setMel(0);
    }
  }, [kuantiti, harga, diskon, selectedCustomerId, selectedBarangId, customerList, barangList]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Validations
    if (!tanggal) return setErrorMsg('Tanggal wajib diisi.');
    if (!noInvoice.trim()) return setErrorMsg('Nomor Invoice/DO wajib diisi.');
    if (!selectedNoPolisi) return setErrorMsg('Nomor Polisi wajib dipilih.');
    if (!selectedCustomerId) return setErrorMsg('Customer wajib dipilih.');
    if (!selectedBarangId) return setErrorMsg('Barang/Material wajib dipilih.');
    if (kuantiti <= 0) return setErrorMsg('Kuantiti harus lebih besar dari 0.');
    if (harga < 0) return setErrorMsg('Harga tidak boleh negatif.');
    if (diskon < 0) return setErrorMsg('Diskon tidak boleh negatif.');
    if (diskon > harga) return setErrorMsg('Diskon tidak boleh melebihi harga barang.');

    const activeVehicle = kendaraanList.find((k) => k.noPolisi === selectedNoPolisi);
    const activeCustomer = customerList.find((c) => c.id === selectedCustomerId);
    const activeBarang = barangList.find((b) => b.id === selectedBarangId);
    const activeAlatBerat = alatBeratList.find((a) => a.id === selectedAlatBeratId);

    if (!activeVehicle || !activeCustomer || !activeBarang) {
      return setErrorMsg('Data master yang diintegrasikan tidak valid atau telah dihapus.');
    }

    const payload = {
      tanggal,
      divisi,
      tipePenjualan,
      noInvoice: noInvoice.trim(),
      noPolisi: activeVehicle.noPolisi,
      statusKendaraan: activeVehicle.statusKendaraan,
      sopir: activeVehicle.sopir,
      kodeCustomer: activeCustomer.kodeCustomer,
      namaCustomer: activeCustomer.namaCustomer,
      kodeBarang: activeBarang.kodeBarang,
      namaBarang: activeBarang.namaBarang,
      satuan,
      kuantiti,
      harga,
      diskon,
      total,
      keterangan: keterangan.trim(),
      kodeAlat: activeAlatBerat ? activeAlatBerat.kodeAlat : '',
      namaAlat: activeAlatBerat ? activeAlatBerat.namaAlat : '',
      mel,
    };

    if (initialData) {
      onSubmit({ ...payload, id: initialData.id });
    } else {
      onSubmit(payload);
    }
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      {errorMsg && (
        <div className="flex items-start gap-2 p-2.5 text-xs font-bold bg-rose-50 text-rose-700 rounded-sm border border-rose-300">
          <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
          <div>{errorMsg}</div>
        </div>
      )}

      {/* SECTION 1: Transaksi Dasar */}
      <div className="bg-white p-3 rounded-sm border border-slate-300 space-y-3">
        <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-200 pb-1.5">
          1. Informasi Transaksi &amp; Divisi
        </h4>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Tanggal Transaksi <span className="text-rose-500">*</span>
            </label>
            <input
              id="form-tanggal"
              type="date"
              required
              value={tanggal}
              onChange={(e) => setTanggal(e.target.value)}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500 font-mono"
            />
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Divisi <span className="text-rose-500">*</span>
            </label>
            <select
              value={divisi}
              onChange={(e) => setDivisi(e.target.value as Penjualan['divisi'])}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            >
              <option value="Tambang">Tambang</option>
              <option value="Cucian">Cucian</option>
              <option value="Transportasi">Transportasi</option>
              <option value="Alat Berat">Alat Berat</option>
              <option value="Holding">Holding</option>
              <option value="Magetan">Magetan</option>
            </select>
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Tipe Penjualan <span className="text-rose-500">*</span>
            </label>
            <select
              value={tipePenjualan}
              onChange={(e) => setTipePenjualan(e.target.value as Penjualan['tipePenjualan'])}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            >
              <option value="Tunai">Tunai (Cash)</option>
              <option value="Non Tunai">Non Tunai</option>
              <option value="Transfer">Transfer</option>
              <option value="DP">DP (Uang Muka)</option>
            </select>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              No Invoice / DO <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              placeholder="Contoh: INV/2026/07/001"
              value={noInvoice}
              onChange={(e) => {
                setNoInvoice(e.target.value);
                setIsNoInvoiceManuallyEdited(true);
              }}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 placeholder-slate-400 focus:outline-hidden focus:ring-1 focus:ring-blue-500 font-mono"
            />
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Alat Berat Pendukung <span className="text-slate-400">(Opsional)</span>
            </label>
            <select
              value={selectedAlatBeratId}
              onChange={(e) => setSelectedAlatBeratId(e.target.value)}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            >
              <option value="">-- Tanpa Alat Berat --</option>
              {alatBeratList.map((item) => (
                <option key={item.id} value={item.id}>
                  [{item.kodeAlat}] {item.namaAlat}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* SECTION 2: Integrasi Kendaraan & Customer */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Kendaraan */}
        <div className="bg-white p-3 rounded-sm border border-slate-300 space-y-3">
          <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-200 pb-1.5">
            2. Integrasi Database Kendaraan
          </h4>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Pilih No Polisi <span className="text-rose-500">*</span>
            </label>
            <select
              required
              value={selectedNoPolisi}
              onChange={(e) => handleVehicleChange(e.target.value)}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500 font-mono"
            >
              <option value="">-- Pilih Kendaraan --</option>
              {kendaraanList.map((k) => (
                <option key={k.noPolisi} value={k.noPolisi}>
                  {k.noPolisi} ({k.sopir})
                </option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">
                Sopir (Auto)
              </label>
              <div className="px-2 py-1 text-xs bg-slate-100 border border-slate-200 rounded-sm text-slate-600 font-medium h-7 flex items-center">
                {sopir || <span className="text-slate-400 italic">No Polisi belum dipilih</span>}
              </div>
            </div>

            <div>
              <label className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">
                Status Kendaraan (Auto)
              </label>
              <div className="px-2 py-1 text-xs bg-slate-100 border border-slate-200 rounded-sm text-slate-600 font-semibold font-mono h-7 flex items-center">
                {selectedNoPolisi ? (
                  <span
                    className={
                      statusKendaraan === 'INTERNAL'
                        ? 'text-emerald-700 bg-emerald-50 px-1 rounded-xs'
                        : 'text-indigo-700 bg-indigo-50 px-1 rounded-xs'
                    }
                  >
                    {statusKendaraan}
                  </span>
                ) : (
                  <span className="text-slate-400 italic font-sans font-normal">No Polisi belum dipilih</span>
                )}
              </div>
            </div>
          </div>
        </div>

        {/* Customer */}
        <div className="bg-white p-3 rounded-sm border border-slate-300 space-y-3">
          <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-200 pb-1.5">
            3. Integrasi Database Customer
          </h4>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Pilih Customer <span className="text-rose-500">*</span>
            </label>
            <select
              required
              value={selectedCustomerId}
              onChange={(e) => setSelectedCustomerId(e.target.value)}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            >
              <option value="">-- Pilih Customer --</option>
              {customerList.map((c) => (
                <option key={c.id} value={c.id}>
                  [{c.kodeCustomer}] {c.namaCustomer}
                </option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">
                Kode Customer (Auto)
              </label>
              <div className="px-2 py-1 text-xs bg-slate-100 border border-slate-200 rounded-sm text-slate-600 font-semibold font-mono h-7 flex items-center">
                {customerList.find((c) => c.id === selectedCustomerId)?.kodeCustomer || (
                  <span className="text-slate-400 italic font-sans font-normal">Pilih customer</span>
                )}
              </div>
            </div>

            <div>
              <label className="block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">
                Nama Customer (Auto)
              </label>
              <div className="px-2 py-1 text-xs bg-slate-100 border border-slate-200 rounded-sm text-slate-600 font-medium truncate h-7 flex items-center">
                {customerList.find((c) => c.id === selectedCustomerId)?.namaCustomer || (
                  <span className="text-slate-400 italic">Pilih customer</span>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* SECTION 3: Integrasi Barang & Keuangan */}
      <div className="bg-white p-3 rounded-sm border border-slate-300 space-y-3">
        <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest border-b border-slate-200 pb-1.5">
          4. Integrasi Barang &amp; Nilai Transaksi
        </h4>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Pilih Barang / Material <span className="text-rose-500">*</span>
            </label>
            <select
              required
              value={selectedBarangId}
              onChange={(e) => setSelectedBarangId(e.target.value)}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            >
              <option value="">-- Pilih Barang --</option>
              {barangList.map((b) => (
                <option key={b.id} value={b.id}>
                  [{b.kodeBarang}] {b.namaBarang} (MEL: Rp {b.nilaiMel.toLocaleString('id-ID')})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Satuan <span className="text-rose-500">*</span>
            </label>
            <select
              value={satuan}
              onChange={(e) => setSatuan(e.target.value as Penjualan['satuan'])}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 focus:outline-hidden focus:ring-1 focus:ring-blue-500 font-bold"
            >
              <option value="RIT">RIT</option>
              <option value="KUBIK">KUBIK</option>
              <option value="TON">TON</option>
              <option value="TRONTON">TRONTON</option>
            </select>
          </div>
        </div>

        {/* Financial Inputs */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Kuantiti <span className="text-rose-500">*</span>
            </label>
            <input
              type="number"
              required
              min={1}
              step="any"
              placeholder="Contoh: 12"
              value={kuantiti || ''}
              onChange={(e) => setKuantiti(Math.max(0, parseFloat(e.target.value) || 0))}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 placeholder-slate-400 font-mono focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Harga Satuan (Rp) <span className="text-rose-500">*</span>
            </label>
            <input
              type="number"
              required
              min={0}
              placeholder="Contoh: 450000"
              value={harga || ''}
              onChange={(e) => setHarga(Math.max(0, parseInt(e.target.value) || 0))}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 placeholder-slate-400 font-mono focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            />
          </div>

          <div>
            <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
              Diskon Potongan (Rp)
            </label>
            <input
              type="number"
              min={0}
              placeholder="Contoh: 15000"
              value={diskon || ''}
              onChange={(e) => setDiskon(Math.max(0, parseInt(e.target.value) || 0))}
              className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 placeholder-slate-400 font-mono focus:outline-hidden focus:ring-1 focus:ring-blue-500"
            />
          </div>
        </div>

        {/* Integration Summary Display boxes (Total & MEL Live) */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3 pt-3 border-t border-dashed border-slate-300 mt-2">
          {/* MEL calculation box */}
          <div className="bg-slate-50 p-2.5 rounded-sm border border-slate-300 flex items-start gap-2">
            <Info className="w-4 h-4 text-slate-600 shrink-0 mt-0.5" />
            <div>
              <h5 className="text-[9px] font-bold text-slate-600 uppercase tracking-wider">
                Nilai MEL Terhitung (Live)
              </h5>
              <p className="text-sm font-mono font-bold text-slate-800">
                Rp {mel.toLocaleString('id-ID')}
              </p>
              <p className="text-[10px] text-slate-500 mt-0.5">
                {selectedCustomerId &&
                customerList.find((c) => c.id === selectedCustomerId)?.namaCustomer.trim().toLowerCase() ===
                  'manyung' ? (
                  <span className="font-bold text-amber-800 bg-amber-100 px-1 py-0.2 rounded-xs">
                    Cust "Manyung": Otomatis Rp 0
                  </span>
                ) : (
                  <span>Database Barang ({satuan})</span>
                )}
              </p>
            </div>
          </div>

          {/* Formula total box */}
          <div className="bg-slate-50 p-2.5 rounded-sm border border-slate-300 flex items-start gap-2">
            <Calculator className="w-4 h-4 text-blue-600 shrink-0 mt-0.5" />
            <div>
              <h5 className="text-[9px] font-bold text-blue-600 uppercase tracking-wider">
                Total Nilai Penjualan (Live)
              </h5>
              <p className="text-sm font-mono font-bold text-slate-800">
                Rp {total.toLocaleString('id-ID')}
              </p>
              <p className="text-[10px] text-slate-500 mt-0.5">
                Formula: <span className="font-mono text-[10px] font-bold text-blue-800">Qty * (Harga - Diskon)</span>
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Keterangan */}
      <div>
        <label className="block text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">
          Keterangan Tambahan / Catatan DO
        </label>
        <textarea
          placeholder="Tulis keterangan pengiriman atau proyek di sini..."
          rows={2}
          value={keterangan}
          onChange={(e) => setKeterangan(e.target.value)}
          className="w-full px-2 py-1 text-xs border border-slate-300 rounded-sm bg-slate-50 text-slate-700 placeholder-slate-400 focus:outline-hidden focus:ring-1 focus:ring-blue-500 resize-none"
        />
      </div>

      {/* Form Actions */}
      <div className="flex justify-end gap-2 pt-4 border-t border-slate-300 mt-4">
        <button
          type="button"
          onClick={onCancel}
          className="px-3.5 py-1.5 text-xs font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 border border-slate-300 rounded-sm transition-all cursor-pointer uppercase tracking-wider"
        >
          Batal / Kembali
        </button>
        <button
          type="submit"
          className="px-3.5 py-1.5 text-xs font-bold text-white bg-blue-600 hover:bg-blue-700 border border-blue-700 rounded-sm transition-all shadow-sm cursor-pointer uppercase tracking-wider"
        >
          {initialData ? 'Simpan Perubahan' : 'Posting Transaksi'}
        </button>
      </div>
    </form>
  );
}
